### ISSUE TITLE
Could we add a setting to change the path to the lcov.info file?

### ISSUE THREAD

**Issue by elliotaplant** [kentaro-m/coverage-markers#26]
## Type

* [ ] Report a bug
* [x] Request a feature
* [ ] Other

## Description
My new project unfortunately has the coverage file nested and not at `./coverage/lcov.info`
I'll see if I can make a PR for this

## Your Environment

* OS: Mac
* Atom version: 1.28.2
* Coverage measurement tool: Jest default

**Comment by elliotaplant** [comment]
Nevermind - this is already solved!

**Comment by jwir3** [comment]
@elliotaplant How did you fix this? I can't find a settings view for this package...

**Comment by elliotaplant** [comment]
Sorry, I should have left a more descriptive comment. I found that this package was able to find the `lcov.info` file recursively, so there was no need to make a PR. Where is your `lcov.info` file? And is the package showing markers for you?

Check out the [coverage-files.js](https://github.com/kentaro-m/coverage-markers/blob/db802a31b87ee7341e86e416451e18e3f49fe1a6/lib/coverage-file.js#L10-L19) file. You'll see that the `findCoverageFilePath` function has a wildcard glob pattern, so it searches recursively through your entire your project for the `lcov.info` file (except `node_modules`), so it doesn't matter where you put the file, so long as its named `lcov.info`.
